### ISSUE TITLE
videos/add接口报错没有account_id参数

### ISSUE THREAD

**Issue by Joyionline** [TencentAd/marketing-api-go-sdk#12]
videos/add 接口复制的文档代码，一直报错The required parameter is 'account_id',这account_id不是sdk方法都封装好的吗，已经传了报错是什么意思

**Comment by KylinHuang7** [comment]
这边是已经解决了吗？ @Joyionline

**Comment by Joyionline** [comment]
版本升级到最新就好了

**Comment by Joyionline** [comment]
> 这边是已经解决了吗？ @Joyionline

版本升级到最新就好了
