### ISSUE TITLE
model.DailyReportsGetResponseData MarterialId类型错误

### ISSUE THREAD

**Issue by bububa** [TencentAd/marketing-api-go-sdk#13]
model.DailyReportsGetResponseData中定义MaterialId为int64, API返回结果为string, 建议定义为json.Number

返回结果示例：
`{"code":0,"message":"","message_cn":"","data":{"list":[{"ctr":0.0185,"material_id":"260137953","date":"2021-01-05"},{"ctr":0.0151,"material_id":"260137953","date":"2021-01-06"},{"ctr":0.0225,"material_id":"260137953","date":"2021-01-07"},{"ctr":0.0147,"material_id":"260137953","date":"2021-01-08"},{"ctr":0.0167,"material_id":"260137953","date":"2021-01-09"},{"ctr":0.0175,"material_id":"260137953","date":"2021-01-10"},{"ctr":0.0157,"material_id":"260137953","date":"2021-01-11"},{"ctr":0.0182,"material_id":"260137953","date":"2021-01-12"},{"ctr":0.0171,"material_id":"260137953","date":"2021-01-13"},{"ctr":0.0145,"material_id":"260137953","date":"2021-01-14"}],"unfold_query":[],"page_info":{"page":1,"page_size":10,"total_number":601,"total_page":61}},"trace_id":"b9caabfbc48457a4ac556bf80c52ca0e"}`

Error Message
`json: cannot unmarshal string into Go struct field DailyReportsGetListStruct.data.list.material_id of type int64`

**Comment by KylinHuang7** [comment]
我们会进行优化，使接口返回的字段和文档定义相匹配
