### ISSUE TITLE
1.6升级1.7

### ISSUE THREAD

**Issue by cuckooemm** [TencentAd/marketing-api-go-sdk#17]
在我升级SDK版本的时候，需要更新许多字段类型
当然并不是抱怨需要改
而是不太理解为什么基本类型的 tag 已经包含 `json:"omitempty"`的情况下依然把字段类型改为指针类型
这是出于什么考虑

**Comment by cuckooemm** [comment]
是为了某些字段可以保留默认0值么，但没必要全部都要改成这种方式把
之前有一个`EndDate`字段问题(1.6中没有这个问题了)，但使用过程中基本只碰到过这么一个问题，而且也修复了。
这么做是为了考虑以后可能出现的这种问题吗？

**Comment by dingdaofeng** [comment]
@cuckooemm json:"omitempty" 是指基本数据类型在为默认空值时，json序列化时可忽略该字段。但是并不能区分该基本数据类型是未设置还是特意设置成了默认空值。
导致调用api接口时产生与预期不符的错误。
指针可以较好的区分未设置（指针为nil), 和设置空值（指针指向空值）。
全部换成指针是希望一次彻底的升级统一解决类似问题，抱歉这是一次不兼容的升级。后续新增接口的基本数据类型参数都会是指针的形式。
