### ISSUE TITLE
interactiveType 参数错误

### ISSUE THREAD

**Issue by jukylin** [TencentAd/marketing-api-go-sdk#18]
在1.3 版本  调用  [蹊径-创建互动落地页](https://developers.e.qq.com/docs/api/business_assets/pages/xijing_page_interactive_add?version=1.3)  接口
提示：interactiveType: data should be string, data should be equal to one of the allowed values

文档的请求参数是 interactive_page_type ，请求接口也是传了 interactive_page_type。最后把 [interactive_page_type](https://github.com/TencentAd/marketing-api-go-sdk/blob/master/pkg/api/api_xijing_page_interactive.go#L89) 改成 interactive_type 接口就正常了。
所以是文档错了？还是接口错了？

**Comment by KylinHuang7** [comment]
这个是接口的问题，已经修改了。目前应该可以按照文档来传参。
