### ISSUE TITLE
调用 蹊径-创建互动落地页接口报错

### ISSUE THREAD

**Issue by jukylin** [TencentAd/marketing-api-go-sdk#19]
使用Go SDK 调用 蹊径-创建互动落地页接口
解析json报错：json: cannot unmarshal array into Go struct field XgPageInteractiveAddResponse.data of type model.XijingPageInteractiveAddResponseData

响应的json数据：{"data":[{"id":"4627685","message":"\u64cd\u4f5c\u6210\u529f","code":0,"landingPageId":3253611}],"code":0,"message":"","message_cn":""}

**Comment by KylinHuang7** [comment]
请升级最新版Go SDK(1.7.5及以上版本)，已经修复了这个问题
