### ISSUE TITLE
syntax error: unexpected -, expecting semicolon or newline

### ISSUE THREAD

**Issue by kanjie128** [TencentAd/marketing-api-go-sdk#25]
# go get github.com/tencentad/marketing-api-go-sdk
go: downloading github.com/tencentad/marketing-api-go-sdk v1.7.11
#github.com/tencentad/marketing-api-go-sdk
/root/go/pkg/mod/github.com/tencentad/marketing-api-go-sdk@v1.7.11/main.go:1:18: syntax error: unexpected -, expecting semicolon or newline

**Comment by dingdaofeng** [comment]
切换到‘marketing_api_go_sdk’
