### ISSUE TITLE
关于限流...

### ISSUE THREAD

**Issue by hwzp99** [TencentAd/marketing-api-go-sdk#27]
{"code":30104,"message":"Request limit reached. Please retry after one minute. trace_id: faafabb4262fe68edd5673fbbb9e8ea0","message_cn":"已达到请求限制。 请在一分钟后重试。 trace_id: faafabb4262fe68edd5673fbbb9e8ea0"}

自己记录了访问频次，qps很低，远没到访问限制。但是程序访问返回了 30104..反馈中心只会回复让走异步接口，毫无帮助...
请问一下，有没有途径或者联系方式可以推进该问题接下来如何定位的，谢谢🙏

**Comment by KylinHuang7** [comment]
这块不是SDK层面的问题了，以反馈中心的回复为准……
频次可能是app_id(应用)维度的，不一定是account_id维度的，建议找反馈中心去了解下具体的频次限制是多少。
