### ISSUE TITLE
创建广告创意报错 'image_id' is invalid

### ISSUE THREAD

**Issue by Michael-LiK** [TencentAd/marketing-api-go-sdk#28]
{"code":31034,"message":"Parameter 'image_id' is invalid. trace_id: 791d2acc0b96d55b8dca080672f65e3a","message_cn":"参数image_id无效或者不合法，请检查该参数。 trace_id: 791d2acc0b96d55b8dca080672f65e3a"} 
我确认了好几遍，自己的image格式正确无误，希望能帮忙解答下，找了客服，一直没回复，谢谢了。

**Comment by KylinHuang7** [comment]
检查下brand_img字段吧。这不是SDK相关问题，可以从反馈中心咨询，这边先关闭issue了。
