### ISSUE TITLE
errors while installing

### ISSUE THREAD

**Issue by twtfnswc** [TencentAd/marketing-api-go-sdk#4]
go get -u github.com/tencentad/marketing-api-go-sdk
package github.com/tencentad/marketing-api-go-sdk: no Go files in /Users/***/go/src/github.com/tencentad/marketing-api-go-sdk

**Comment by CraryPrimitiveMan** [comment]
@twtfnswc 加上版本号尝试一下呢？
go get -u github.com/tencentad/marketing-api-go-sdk@v1.1.0

**Comment by CraryPrimitiveMan** [comment]
@twtfnswc 已处理
