### ISSUE TITLE
视频上传接口bug

### ISSUE THREAD

**Issue by xiongxch** [TencentAd/marketing-api-go-sdk#7]
[接口文档](https://developers.e.qq.com/docs/api/business_assets/video/videos_add?version=1.1#wu4b1)
上传参数中的key为video_file 这个字段是必传的。[SDK代码中文件视频上传也是用file作为字段](https://github.com/TencentAd/marketing-api-go-sdk/blob/master/pkg/api/client.go#L508)，所以接口调试不通

**Comment by CraryPrimitiveMan** [comment]
@xiongxch 已修复，v1.2.0版本
