### ISSUE TITLE
获取推广目标响应结构体与接口文档不一致

### ISSUE THREAD

**Issue by xiongxch** [TencentAd/marketing-api-go-sdk#8]
[`mapi`](https://developers.e.qq.com/docs/api/business_assets/promoted_objects/promoted_objects_get?version=1.3&_preview=1)

**Comment by CraryPrimitiveMan** [comment]
@xiongxch 收到，我们尽快处理一下

**Comment by CraryPrimitiveMan** [comment]
@xiongxch 已调整
