### ISSUE TITLE
目前go SDK 1.2.0版本支持腾讯广告文档v1.3版本接口吗？

### ISSUE THREAD

**Issue by php2go** [TencentAd/marketing-api-go-sdk#9]
### 目前go SDK 1.2.0版本支持腾讯广告文档v1.3版本接口吗？

![image](https://user-images.githubusercontent.com/16772742/90230099-9c097380-de4b-11ea-9494-2be957bebad9.png)

**Comment by CraryPrimitiveMan** [comment]
可以支持的，可以通过修改SDKClient的ApiVersion指定接口版本号
